### ISSUE TITLE
[CompletionException: java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute]

### ISSUE THREAD

**Issue by Hawk707** [playframework/play-java-fileupload-example#11]
When I try to run Beaker Notebook on Windows, I get the following stack trace:

```
[error]

 application - 

! @736n7a5id - Internal server error, for (POST) [/upload] ->

 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
Caused by: java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:222)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at controllers.MyMultipartFormDataBodyParser.generateTempFile(MyMultipartFormDataBodyParser.java:72)
	at controllers.MyMultipartFormDataBodyParser.lambda$createFilePartHandler$1(MyMultipartFormDataBodyParser.java:49)
	at controllers.DelegatingMultipartFormDataBodyParser$ScalaFilePartHandler.apply(DelegatingMultipartFormDataBodyParser.java:61)

```

java version "1.8.0_111"
IDE: IntelliJ 14

**Comment by coolbhushan** [comment]
This issue is on windows, As windows do not support POSIX file attributes.  So a workaround is to remove file attributes or specify in windows manner.  Just comment POSIX attributes lines in genrateTempFile function.

private File generateTempFile() {
        try {
           // final EnumSet<PosixFilePermission> attrs = EnumSet.of(OWNER_READ, OWNER_WRITE);
          //  final FileAttribute<?> attr = PosixFilePermissions.asFileAttribute(attrs);
            final Path path = Files.createTempFile("multipartBody", "tempFile");
            return path.toFile();
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }

**Comment by wsargent** [comment]
Can you submit a PR and I'll merge it?
